<?php
/**
 * Global functions.
 *
 * @author  Ajit Bohra <ajit@lubus.in>
 * @license MIT
 *
 * @see   https://www.munim.com/
 *
 * @copyright 2019 LUBUS
 * @package   Munim
 */

/**
 * Get Base Currency Code.
 *
 * @return string
 */
function get_munim_currency() {
	$munim_business_settings = get_option( 'munim_settings_business' );
	$munim_currency          = isset( $munim_business_settings['currency'] ) ? $munim_business_settings['currency'] : 'INR';
	return apply_filters( 'munim_currency', $munim_currency );
}

/**
 * Get full list of currency codes.
 *
 * @return array
 */
function get_munim_currencies() {
	static $currencies;
	if ( ! isset( $currencies ) ) {
		$currencies = array_unique(
			apply_filters(
				'munim_currencies',
				array(
					'AED' => __( 'United Arab Emirates dirham', 'munim' ),
					'AFN' => __( 'Afghan afghani', 'munim' ),
					'ALL' => __( 'Albanian lek', 'munim' ),
					'AMD' => __( 'Armenian dram', 'munim' ),
					'ANG' => __( 'Netherlands Antillean guilder', 'munim' ),
					'AOA' => __( 'Angolan kwanza', 'munim' ),
					'ARS' => __( 'Argentine peso', 'munim' ),
					'AUD' => __( 'Australian dollar', 'munim' ),
					'AWG' => __( 'Aruban florin', 'munim' ),
					'AZN' => __( 'Azerbaijani manat', 'munim' ),
					'BAM' => __( 'Bosnia and Herzegovina convertible mark', 'munim' ),
					'BBD' => __( 'Barbadian dollar', 'munim' ),
					'BDT' => __( 'Bangladeshi taka', 'munim' ),
					'BGN' => __( 'Bulgarian lev', 'munim' ),
					'BHD' => __( 'Bahraini dinar', 'munim' ),
					'BIF' => __( 'Burundian franc', 'munim' ),
					'BMD' => __( 'Bermudian dollar', 'munim' ),
					'BND' => __( 'Brunei dollar', 'munim' ),
					'BOB' => __( 'Bolivian boliviano', 'munim' ),
					'BRL' => __( 'Brazilian real', 'munim' ),
					'BSD' => __( 'Bahamian dollar', 'munim' ),
					'BTC' => __( 'Bitcoin', 'munim' ),
					'BTN' => __( 'Bhutanese ngultrum', 'munim' ),
					'BWP' => __( 'Botswana pula', 'munim' ),
					'BYR' => __( 'Belarusian ruble (old)', 'munim' ),
					'BYN' => __( 'Belarusian ruble', 'munim' ),
					'BZD' => __( 'Belize dollar', 'munim' ),
					'CAD' => __( 'Canadian dollar', 'munim' ),
					'CDF' => __( 'Congolese franc', 'munim' ),
					'CHF' => __( 'Swiss franc', 'munim' ),
					'CLP' => __( 'Chilean peso', 'munim' ),
					'CNY' => __( 'Chinese yuan', 'munim' ),
					'COP' => __( 'Colombian peso', 'munim' ),
					'CRC' => __( 'Costa Rican col&oacute;n', 'munim' ),
					'CUC' => __( 'Cuban convertible peso', 'munim' ),
					'CUP' => __( 'Cuban peso', 'munim' ),
					'CVE' => __( 'Cape Verdean escudo', 'munim' ),
					'CZK' => __( 'Czech koruna', 'munim' ),
					'DJF' => __( 'Djiboutian franc', 'munim' ),
					'DKK' => __( 'Danish krone', 'munim' ),
					'DOP' => __( 'Dominican peso', 'munim' ),
					'DZD' => __( 'Algerian dinar', 'munim' ),
					'EGP' => __( 'Egyptian pound', 'munim' ),
					'ERN' => __( 'Eritrean nakfa', 'munim' ),
					'ETB' => __( 'Ethiopian birr', 'munim' ),
					'EUR' => __( 'Euro', 'munim' ),
					'FJD' => __( 'Fijian dollar', 'munim' ),
					'FKP' => __( 'Falkland Islands pound', 'munim' ),
					'GBP' => __( 'Pound sterling', 'munim' ),
					'GEL' => __( 'Georgian lari', 'munim' ),
					'GGP' => __( 'Guernsey pound', 'munim' ),
					'GHS' => __( 'Ghana cedi', 'munim' ),
					'GIP' => __( 'Gibraltar pound', 'munim' ),
					'GMD' => __( 'Gambian dalasi', 'munim' ),
					'GNF' => __( 'Guinean franc', 'munim' ),
					'GTQ' => __( 'Guatemalan quetzal', 'munim' ),
					'GYD' => __( 'Guyanese dollar', 'munim' ),
					'HKD' => __( 'Hong Kong dollar', 'munim' ),
					'HNL' => __( 'Honduran lempira', 'munim' ),
					'HRK' => __( 'Croatian kuna', 'munim' ),
					'HTG' => __( 'Haitian gourde', 'munim' ),
					'HUF' => __( 'Hungarian forint', 'munim' ),
					'IDR' => __( 'Indonesian rupiah', 'munim' ),
					'ILS' => __( 'Israeli new shekel', 'munim' ),
					'IMP' => __( 'Manx pound', 'munim' ),
					'INR' => __( 'Indian rupee', 'munim' ),
					'IQD' => __( 'Iraqi dinar', 'munim' ),
					'IRR' => __( 'Iranian rial', 'munim' ),
					'IRT' => __( 'Iranian toman', 'munim' ),
					'ISK' => __( 'Icelandic kr&oacute;na', 'munim' ),
					'JEP' => __( 'Jersey pound', 'munim' ),
					'JMD' => __( 'Jamaican dollar', 'munim' ),
					'JOD' => __( 'Jordanian dinar', 'munim' ),
					'JPY' => __( 'Japanese yen', 'munim' ),
					'KES' => __( 'Kenyan shilling', 'munim' ),
					'KGS' => __( 'Kyrgyzstani som', 'munim' ),
					'KHR' => __( 'Cambodian riel', 'munim' ),
					'KMF' => __( 'Comorian franc', 'munim' ),
					'KPW' => __( 'North Korean won', 'munim' ),
					'KRW' => __( 'South Korean won', 'munim' ),
					'KWD' => __( 'Kuwaiti dinar', 'munim' ),
					'KYD' => __( 'Cayman Islands dollar', 'munim' ),
					'KZT' => __( 'Kazakhstani tenge', 'munim' ),
					'LAK' => __( 'Lao kip', 'munim' ),
					'LBP' => __( 'Lebanese pound', 'munim' ),
					'LKR' => __( 'Sri Lankan rupee', 'munim' ),
					'LRD' => __( 'Liberian dollar', 'munim' ),
					'LSL' => __( 'Lesotho loti', 'munim' ),
					'LYD' => __( 'Libyan dinar', 'munim' ),
					'MAD' => __( 'Moroccan dirham', 'munim' ),
					'MDL' => __( 'Moldovan leu', 'munim' ),
					'MGA' => __( 'Malagasy ariary', 'munim' ),
					'MKD' => __( 'Macedonian denar', 'munim' ),
					'MMK' => __( 'Burmese kyat', 'munim' ),
					'MNT' => __( 'Mongolian t&ouml;gr&ouml;g', 'munim' ),
					'MOP' => __( 'Macanese pataca', 'munim' ),
					'MRO' => __( 'Mauritanian ouguiya', 'munim' ),
					'MUR' => __( 'Mauritian rupee', 'munim' ),
					'MVR' => __( 'Maldivian rufiyaa', 'munim' ),
					'MWK' => __( 'Malawian kwacha', 'munim' ),
					'MXN' => __( 'Mexican peso', 'munim' ),
					'MYR' => __( 'Malaysian ringgit', 'munim' ),
					'MZN' => __( 'Mozambican metical', 'munim' ),
					'NAD' => __( 'Namibian dollar', 'munim' ),
					'NGN' => __( 'Nigerian naira', 'munim' ),
					'NIO' => __( 'Nicaraguan c&oacute;rdoba', 'munim' ),
					'NOK' => __( 'Norwegian krone', 'munim' ),
					'NPR' => __( 'Nepalese rupee', 'munim' ),
					'NZD' => __( 'New Zealand dollar', 'munim' ),
					'OMR' => __( 'Omani rial', 'munim' ),
					'PAB' => __( 'Panamanian balboa', 'munim' ),
					'PEN' => __( 'Sol', 'munim' ),
					'PGK' => __( 'Papua New Guinean kina', 'munim' ),
					'PHP' => __( 'Philippine peso', 'munim' ),
					'PKR' => __( 'Pakistani rupee', 'munim' ),
					'PLN' => __( 'Polish z&#x142;oty', 'munim' ),
					'PRB' => __( 'Transnistrian ruble', 'munim' ),
					'PYG' => __( 'Paraguayan guaran&iacute;', 'munim' ),
					'QAR' => __( 'Qatari riyal', 'munim' ),
					'RON' => __( 'Romanian leu', 'munim' ),
					'RSD' => __( 'Serbian dinar', 'munim' ),
					'RUB' => __( 'Russian ruble', 'munim' ),
					'RWF' => __( 'Rwandan franc', 'munim' ),
					'SAR' => __( 'Saudi riyal', 'munim' ),
					'SBD' => __( 'Solomon Islands dollar', 'munim' ),
					'SCR' => __( 'Seychellois rupee', 'munim' ),
					'SDG' => __( 'Sudanese pound', 'munim' ),
					'SEK' => __( 'Swedish krona', 'munim' ),
					'SGD' => __( 'Singapore dollar', 'munim' ),
					'SHP' => __( 'Saint Helena pound', 'munim' ),
					'SLL' => __( 'Sierra Leonean leone', 'munim' ),
					'SOS' => __( 'Somali shilling', 'munim' ),
					'SRD' => __( 'Surinamese dollar', 'munim' ),
					'SSP' => __( 'South Sudanese pound', 'munim' ),
					'STD' => __( 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe dobra', 'munim' ),
					'SYP' => __( 'Syrian pound', 'munim' ),
					'SZL' => __( 'Swazi lilangeni', 'munim' ),
					'THB' => __( 'Thai baht', 'munim' ),
					'TJS' => __( 'Tajikistani somoni', 'munim' ),
					'TMT' => __( 'Turkmenistan manat', 'munim' ),
					'TND' => __( 'Tunisian dinar', 'munim' ),
					'TOP' => __( 'Tongan pa&#x2bb;anga', 'munim' ),
					'TRY' => __( 'Turkish lira', 'munim' ),
					'TTD' => __( 'Trinidad and Tobago dollar', 'munim' ),
					'TWD' => __( 'New Taiwan dollar', 'munim' ),
					'TZS' => __( 'Tanzanian shilling', 'munim' ),
					'UAH' => __( 'Ukrainian hryvnia', 'munim' ),
					'UGX' => __( 'Ugandan shilling', 'munim' ),
					'USD' => __( 'United States (US) dollar', 'munim' ),
					'UYU' => __( 'Uruguayan peso', 'munim' ),
					'UZS' => __( 'Uzbekistani som', 'munim' ),
					'VEF' => __( 'Venezuelan bol&iacute;var', 'munim' ),
					'VES' => __( 'Bol&iacute;var soberano', 'munim' ),
					'VND' => __( 'Vietnamese &#x111;&#x1ed3;ng', 'munim' ),
					'VUV' => __( 'Vanuatu vatu', 'munim' ),
					'WST' => __( 'Samoan t&#x101;l&#x101;', 'munim' ),
					'XAF' => __( 'Central African CFA franc', 'munim' ),
					'XCD' => __( 'East Caribbean dollar', 'munim' ),
					'XOF' => __( 'West African CFA franc', 'munim' ),
					'XPF' => __( 'CFP franc', 'munim' ),
					'YER' => __( 'Yemeni rial', 'munim' ),
					'ZAR' => __( 'South African rand', 'munim' ),
					'ZMW' => __( 'Zambian kwacha', 'munim' ),
				)
			)
		);
	}
	return $currencies;
}

/**
 * Get Currency symbol.
 *
 * @param string $currency Currency. (default: '').
 * @return string
 */
function get_munim_currency_symbol( $currency = '' ) {
	if ( ! $currency ) {
		$currency = get_munim_currency();
	}
	$symbols         = apply_filters(
		'munim_currency_symbols',
		array(
			'AED' => '&#x62f;.&#x625;',
			'AFN' => '&#x60b;',
			'ALL' => 'L',
			'AMD' => 'AMD',
			'ANG' => '&fnof;',
			'AOA' => 'Kz',
			'ARS' => '&#36;',
			'AUD' => '&#36;',
			'AWG' => 'Afl.',
			'AZN' => 'AZN',
			'BAM' => 'KM',
			'BBD' => '&#36;',
			'BDT' => '&#2547;&nbsp;',
			'BGN' => '&#1083;&#1074;.',
			'BHD' => '.&#x62f;.&#x628;',
			'BIF' => 'Fr',
			'BMD' => '&#36;',
			'BND' => '&#36;',
			'BOB' => 'Bs.',
			'BRL' => '&#82;&#36;',
			'BSD' => '&#36;',
			'BTC' => '&#3647;',
			'BTN' => 'Nu.',
			'BWP' => 'P',
			'BYR' => 'Br',
			'BYN' => 'Br',
			'BZD' => '&#36;',
			'CAD' => '&#36;',
			'CDF' => 'Fr',
			'CHF' => '&#67;&#72;&#70;',
			'CLP' => '&#36;',
			'CNY' => '&yen;',
			'COP' => '&#36;',
			'CRC' => '&#x20a1;',
			'CUC' => '&#36;',
			'CUP' => '&#36;',
			'CVE' => '&#36;',
			'CZK' => '&#75;&#269;',
			'DJF' => 'Fr',
			'DKK' => 'DKK',
			'DOP' => 'RD&#36;',
			'DZD' => '&#x62f;.&#x62c;',
			'EGP' => 'EGP',
			'ERN' => 'Nfk',
			'ETB' => 'Br',
			'EUR' => '&euro;',
			'FJD' => '&#36;',
			'FKP' => '&pound;',
			'GBP' => '&pound;',
			'GEL' => '&#x20be;',
			'GGP' => '&pound;',
			'GHS' => '&#x20b5;',
			'GIP' => '&pound;',
			'GMD' => 'D',
			'GNF' => 'Fr',
			'GTQ' => 'Q',
			'GYD' => '&#36;',
			'HKD' => '&#36;',
			'HNL' => 'L',
			'HRK' => 'kn',
			'HTG' => 'G',
			'HUF' => '&#70;&#116;',
			'IDR' => 'Rp',
			'ILS' => '&#8362;',
			'IMP' => '&pound;',
			'INR' => '&#8377;',
			'IQD' => '&#x639;.&#x62f;',
			'IRR' => '&#xfdfc;',
			'IRT' => '&#x062A;&#x0648;&#x0645;&#x0627;&#x0646;',
			'ISK' => 'kr.',
			'JEP' => '&pound;',
			'JMD' => '&#36;',
			'JOD' => '&#x62f;.&#x627;',
			'JPY' => '&yen;',
			'KES' => 'KSh',
			'KGS' => '&#x441;&#x43e;&#x43c;',
			'KHR' => '&#x17db;',
			'KMF' => 'Fr',
			'KPW' => '&#x20a9;',
			'KRW' => '&#8361;',
			'KWD' => '&#x62f;.&#x643;',
			'KYD' => '&#36;',
			'KZT' => 'KZT',
			'LAK' => '&#8365;',
			'LBP' => '&#x644;.&#x644;',
			'LKR' => '&#xdbb;&#xdd4;',
			'LRD' => '&#36;',
			'LSL' => 'L',
			'LYD' => '&#x644;.&#x62f;',
			'MAD' => '&#x62f;.&#x645;.',
			'MDL' => 'MDL',
			'MGA' => 'Ar',
			'MKD' => '&#x434;&#x435;&#x43d;',
			'MMK' => 'Ks',
			'MNT' => '&#x20ae;',
			'MOP' => 'P',
			'MRO' => 'UM',
			'MUR' => '&#x20a8;',
			'MVR' => '.&#x783;',
			'MWK' => 'MK',
			'MXN' => '&#36;',
			'MYR' => '&#82;&#77;',
			'MZN' => 'MT',
			'NAD' => '&#36;',
			'NGN' => '&#8358;',
			'NIO' => 'C&#36;',
			'NOK' => '&#107;&#114;',
			'NPR' => '&#8360;',
			'NZD' => '&#36;',
			'OMR' => '&#x631;.&#x639;.',
			'PAB' => 'B/.',
			'PEN' => 'S/',
			'PGK' => 'K',
			'PHP' => '&#8369;',
			'PKR' => '&#8360;',
			'PLN' => '&#122;&#322;',
			'PRB' => '&#x440;.',
			'PYG' => '&#8370;',
			'QAR' => '&#x631;.&#x642;',
			'RMB' => '&yen;',
			'RON' => 'lei',
			'RSD' => '&#x434;&#x438;&#x43d;.',
			'RUB' => '&#8381;',
			'RWF' => 'Fr',
			'SAR' => '&#x631;.&#x633;',
			'SBD' => '&#36;',
			'SCR' => '&#x20a8;',
			'SDG' => '&#x62c;.&#x633;.',
			'SEK' => '&#107;&#114;',
			'SGD' => '&#36;',
			'SHP' => '&pound;',
			'SLL' => 'Le',
			'SOS' => 'Sh',
			'SRD' => '&#36;',
			'SSP' => '&pound;',
			'STD' => 'Db',
			'SYP' => '&#x644;.&#x633;',
			'SZL' => 'L',
			'THB' => '&#3647;',
			'TJS' => '&#x405;&#x41c;',
			'TMT' => 'm',
			'TND' => '&#x62f;.&#x62a;',
			'TOP' => 'T&#36;',
			'TRY' => '&#8378;',
			'TTD' => '&#36;',
			'TWD' => '&#78;&#84;&#36;',
			'TZS' => 'Sh',
			'UAH' => '&#8372;',
			'UGX' => 'UGX',
			'USD' => '&#36;',
			'UYU' => '&#36;',
			'UZS' => 'UZS',
			'VEF' => 'Bs F',
			'VES' => 'Bs.S',
			'VND' => '&#8363;',
			'VUV' => 'Vt',
			'WST' => 'T',
			'XAF' => 'CFA',
			'XCD' => '&#36;',
			'XOF' => 'CFA',
			'XPF' => 'Fr',
			'YER' => '&#xfdfc;',
			'ZAR' => '&#82;',
			'ZMW' => 'ZK',
		)
	);
	$currency_symbol = isset( $symbols[ $currency ] ) ? $symbols[ $currency ] : '';
	return apply_filters( 'munim_currency_symbol', $currency_symbol, $currency );
}
